### ISSUE TITLE
Dupe Glitch

### ISSUE THREAD

**Issue by xMikey** [apavarino/Deadchest#10]
- Plugin version Latest
- Minecraft version 1.17
- Server type Paper

Not sure if this is relevant or something fixable or even this plugins fault but
If you combine DeadChest with this plugin [Portable Chests ](https://www.spigotmc.org/resources/portablechests-a-vanilla-like-containers-transporting-plugin-1-14-1-15-1-16-1-17.91260/) it creates the possibility to dupe, because if you place a container holding items next to an active deadchest it breaks the chest dropping the items however the chest also goes back into inventory holding the original items.

**Comment by SoulLength** [comment]
Fixed the issue from my plugin in the new release -> [Portable Chests v1.4.0](https://www.spigotmc.org/resources/portablechests-a-vanilla-like-containers-transporting-plugin-1-14-1-15-1-16-1-17.91260/), you can find the details [here](https://github.com/SoulLength/PortableChests/issues/3#issuecomment-869183486)
