### ISSUE TITLE
Toggle container type in config

### ISSUE THREAD

**Issue by Zoro-6191** [apavarino/Deadchest#11]
I would like a config field in which I can change deadchest type to a barrel or any other container like shulkerbox or enderchest

I had this idea after seeing this one [plugin](https://www.spigotmc.org/resources/deathbarrel.67621/) which used barrels instead of chests and it kinda felt better to me

Let me know if this a good idea or not.

**Comment by apavarino** [comment]
Yes it's an exellent idea. The code is almost ready for that because we already can choose between player head and chest. I will add more container like barrel or shulker box. Thanks for your suggestion !

**Comment by Zoro-6191** [comment]
no thank you for working on it  :)

**Comment by apavarino** [comment]
Added in 4.6.0

**Comment by Zoro-6191** [comment]
nice

**Comment by Zoro-6191** [comment]
btw, it'd be great if you could get the plugin to [https://www.spigotmc.org/](https://www.spigotmc.org/), since they got update notification n all
