### ISSUE TITLE
DeadChest does not expire when chunk is not loaded

### ISSUE THREAD

**Issue by CubeSurv** [apavarino/Deadchest#13]
**Context**
- DeadChest
- 4.4.0
- 1.16.5
- Purpur 1171

**Describe the bug**
DeadChest does not expire when chunk is not loaded. I am set 1 hour for pickup. This is a problem because no more chest will be created once the DeadChest limit is exceeded. 

**To Reproduce**
1. Kill yourself
2. Don't pick up a deadchest 
3.The set time has passed and the deadchest is still active because no one has loaded the chunk.
4.If we have several such chests that have passed the time and if we exceed the limit, the next ones will not be created.

**Expected behavior**
Unloaded chunks should not count towards your deadchest limit. 

**Screenshots**
https://i.imgur.com/WOQWBTf.png

**Comment by apavarino** [comment]
Fixed for 4.7.0

**Comment by CubeSurv** [comment]
> Fixed for 4.7.0

When will it be available to the public?

**Comment by apavarino** [comment]
The version 4.7.0 is currently under Bukkit staff validation. That's should take max 48h to be release :)
