### ISSUE TITLE
config override on server restart

### ISSUE THREAD

**Issue by darkBoft** [apavarino/Deadchest#16]
**Context**
- DeadChest
- 4.6.0
- 1.17.1
- Paper
- Ubuntu 20.06
- Adopt openJDK 16

**Describe the bug**
After starting the server to generate config file and manipulating config.yml, every restart of minecraft server will override manipulated config files.

In the start log is logged something like "config change detected, generate new config file" (sorry, cannot access the server log right now)

After restarting minecraft server, my conifg.yml will be renamed to conifg.old.yml and the default config will be "re-generated" with default values. 

Only solution to this is change the config on server and /dc reload them.

**Comment by apavarino** [comment]
Hi @darkBoft,

The plugin do this behavior when it detect a missing parameter (after an update for example with new feature parameter for example).  If you have all parameter set, the plugin stop to generate defaut config and renaming your congif.old.yml.

Is this behaviour your are reporting ?

Are maybe there is an issue with that and even you have all parameters that trigger the new config generation ?

**Comment by darkBoft** [comment]
Hi @apavarino 

strange on my end, I was wondering the whole time why my configuration was not set but since a week the config is steady and set.

![image](https://user-images.githubusercontent.com/5717122/131234821-e4ae285c-20df-446b-b946-3d2fb7321f84.png)

As you can see, reboot on 25. August was the first time, the config was not changed, regarding to the logfile.

Maybe I was not able to figure it out correctly that the config has not changed.

Thanks for the explanation,

Best Regards,
Björn
