### ISSUE TITLE
Dead Chest spawning bug [1.18 Deeper Caves Datapack related]

### ISSUE THREAD

**Issue by Rexvivor** [apavarino/Deadchest#21]
when a player dies under y0, instead of the dead chest spawning where the player died, it spawns over y0, at either:
-on top of the highest block in that y axis
-a location near that area
-on the lowest y axis that doesn't have a block there

Our server has the Caves & Cliffs datapack in it

**Comment by apavarino** [comment]
Fixed on 4.8.0
