### ISSUE TITLE
 Hologram does not disappear even when using the repair command

### ISSUE THREAD

**Issue by Zmyrna** [apavarino/Deadchest#23]
**Context**
- deadchest
- lastest version
- 1.17.1
- paper

**Describe the bug**
There is a hologram floating, so I go there, but there is no chest and time does not pass.
It does not disappear even after using the repair command.
A record of that player as seen in the deadchest.log

[2021-10-08 23:58:45] Deadchest of [TinonTriNitro] has expired in world

And player of screenshot is offline.
(I don't speak English, so I wrote this using a translator.)

**To Reproduce**

**Expected behavior**

**Screenshots**

![2021-10-09_10 03 55](https://user-images.githubusercontent.com/92192004/136638692-c490aa1b-a37f-4e50-a2b1-b85106a86c51.png)

**Comment by apavarino** [comment]
Fixed on 4.8.0
