### ISSUE TITLE
Disappearing timer 

### ISSUE THREAD

**Issue by CubeSurv** [apavarino/Deadchest#26]
**Context**
- Plugin name  DeadChest
- Plugin version 4 .7.0
- Minecraft version 1.17
- Server type (Bukkit/Spigot/Paper...) Paper

**Describe the bug**
Disappearing timer after approaching the chest. 

**To Reproduce**
Get closer to the deadchest, walk away, and then approach it again

**Video**
https://www.youtube.com/watch?v=rQctSwIkMX0

**Comment by apavarino** [comment]
Wow, strange one. Thanks for the good report and the video !

**Comment by apavarino** [comment]
It looks like a client side issue. No action to do here
