### ISSUE TITLE
Netherite Boots in place of the chestplate

### ISSUE THREAD

**Issue by CubeSurv** [apavarino/Deadchest#27]
**Context**
- Plugin name DeadChest 
- Plugin version 4.7.0
- Minecraft version 1.17
- Server type (Bukkit/Spigot/Paper...) Paper

**Describe the bug**
Netherite Boots in place of the chestplate

**To Reproduce**
1. Wear nether boots and have other types of boot in your inventory
2. Die
4. Pick up DeadChest

**Video**
https://youtu.be/LlADZU0oT8A

**Comment by apavarino** [comment]
This issue will be fixed on the next version :)

Thanks !

**Comment by apavarino** [comment]
Fixed on 4.8.0
