### ISSUE TITLE
Deadchest disappear when person logs off

### ISSUE THREAD

**Issue by Falco-22** [apavarino/Deadchest#29]
Hi, I am a fan of your plugin. I am going to release my own smp. But there is a problem in the plugin. You see when a person dies there's
a deathchest where he died. But If he logs off then the deathchest disappears. And If someone kills a person and wants to get his items then he logs off, it would be very frustrating. So, I hope that you will be kind to get a solution for this problem. 
Thanks,
A Fan

**Comment by apavarino** [comment]
Hi ! Thanks you ! 👍 

Currently it's possible to get the chest of an offline player.

So, If I understand well, you want that's the timer of someone stop decrease when he is offline ?


A developer.

**Comment by Falco-22** [comment]
Oh, I didnt check if the chest was possible to get of an offline player. Sorry, for the inconvenience.

**Comment by apavarino** [comment]
No problem :)
