### ISSUE TITLE
Deadchest spawning on surface when player dies in a deep cave 1.18

### ISSUE THREAD

**Issue by Zoro-6191** [apavarino/Deadchest#30]
**Context**
- Deadchest
- v4.7.0
- 1.18
- Paper #24

**Describe the bug**
I can't say if the player dies below y=0 or if it's a general bug, but the deadchest is spawning on the surface, and the player then needs to go back to the surface to get it back. There's no error in console, just this misbehavior

**To Reproduce**
1. Probably go in a cave below y=0
2. Die
4. Go back

**Comment by apavarino** [comment]
Hi ! it's related to 1.18 version. The plugin not handle y under 0. That will be fixed for the next version.

Thanks for the feedback

**Comment by apavarino** [comment]
Duplicate : https://github.com/apavarino/Deadchest/issues/21

**Comment by apavarino** [comment]
Fixed on 4.8.0
