### ISSUE TITLE
Hologram bug persists after update.

### ISSUE THREAD

**Issue by sebalvaro** [apavarino/Deadchest#31]
**Context**
- Plugin name: DeadChest
- Plugin version: `4.7.0` & `4.8.0`  [--> compiled from source](https://app.circleci.com/pipelines/github/nclz/Deadchest/3/workflows/a9dcda3a-44a2-4c45-afdf-93bbbe9d85e4/jobs/3/artifacts)
- Minecraft version: 1.18
- Server type (Bukkit/Spigot/Paper...): Paper 55

**Describe the bug**
A hologram is still showing after chest destroyed. 
I tried with `/dc repair` but it didn't work

**To Reproduce**
1. I Died with dc 4.7.0
1.1 Hologram get bugged, similar from #23
2. Compiled 4.8.0 (from source)
2.2 Update the plugin from 4.7.0 to 4.8.0
3. Restart Server
4. `/dc repair`
5. Hologram still there.

**Expected behavior**
1. `/dc repair` should remove the hologram.

**Screenshots**
![Screenshot](https://i.imgur.com/4cwLdnH.png)

**Comment by ilfarpro** [comment]
I've just discovered the same issue but in nether. Maybe it's somehow attached to the y height?
Plugin version used 4.8.0

**Comment by JamieD1** [comment]
Getting same issue on 4.7.0 Anyway to remove them?

**Comment by apavarino** [comment]
Just typecthis command next to the holo

`/minecraft:kill @e[sort=nearest,limit=1,type=minecraft:armor_stand]`

**Comment by sebalvaro** [comment]
> Hi,
> 
> Unfortunatly, if you have a corrupted holo on 4.7.0, the update of the plugin will not restore your holo because Deadchest don't know anymore the existence of this holo.
> 
> What you said is a real bug if you have holo generated with version 4.8.0 that's have the same behaviour.
> 
> The real question is : Have you some corrupted holo generate 100% by the 4.8.0 version ?
> 
> 
> 

No, only with 4.7.0, I will try with the command mentioned before.

**Comment by ilfarpro** [comment]
> Hi,
> 
> Unfortunatly, if you have a corrupted holo on 4.7.0, the update of the plugin will not restore your holo because Deadchest don't know anymore the existence of this holo.
> 
> What you said is a real bug if you have holo generated with version 4.8.0 that's have the same behaviour.
> 
> The real question is : Have you some corrupted holo generate 100% by the 4.8.0 version ?

Thanks for information. I expected old holo's will dissapear with plugin update. But then I realized I have to type command you provided. 
/minecraft:kill @e[sort=nearest,limit=1,type=minecraft:armor_stand]

Problem solved.
