### ISSUE TITLE
Error when opening chests

### ISSUE THREAD

**Issue by Pseudonym1911** [apavarino/Deadchest#32]
**Context**
- Plugin name: DeadChest
- Plugin version: 4.8.0
- Minecraft version: 1.18
- Server type (Bukkit/Spigot/Paper...) Bukkit

**Describe the bug**
Receive the error in the picture attached when I open any "chest" item (Deadchest, chest, shulker box, end chest, other plugin Minepacks). Everything seems to be working correctly but I just wanted to bring this up.

**To Reproduce**
Open any "chest" item (Deadchest, chest, shulker box, end chest, other plugin Minepacks).

**Expected behavior**
I'm not sure if this is actually causing any issue but it is an error that is being thrown by the server.

**Screenshots**
![Deadchest error](https://user-images.githubusercontent.com/17224489/145418408-5aa69b0e-45f9-496f-be26-b0e3d7c806c8.PNG)

**Comment by apavarino** [comment]
Thanks for the report !

**Comment by Tikkle** [comment]
Server jar: Purpur 1.18.1
Plugin name: Deadchest
Plugin version: 4.8.0

I had this same error pop up.

**Comment by Tikkle** [comment]
Scratch that, its now constantly spamming it whenever someone enters the nether or end dimensions.

**Comment by sirNugg3ts** [comment]
Server jar: paper-1.18.1-77.jar
Plugin Version: 4.8.0

Having the exact same issue, spams everytime anyone does anything in the nether basicly

**Comment by apavarino** [comment]
Thanks everyone ! 

This issue is fixed on version **4.8.1**.

To get this version :

- Wait for bukkit staff validation and get it on bukkit
- Get it on discord now (https://discord.com/invite/jCsvJxS)
