### ISSUE TITLE
High CPU usage with DeadChest loaded

### ISSUE THREAD

**Issue by kccricket** [apavarino/Deadchest#36]
**Context**
- DeadChest
- 4.8.1
- 1.18.1
- Paper 1.18.1-141

**Describe the bug**
When DeadChest is enabled, the server has extremely high CPU usage. While the server was running, I used PlugMan to unload DeadChest, and CPU usage immediately returned to normal. This was a fresh upgrade from Paper 1.17.1 to 1.18.1 and from DeadChest 4.7.0 to 4.8.1.

**To Reproduce**
Unknown.

Timings: https://timings.aikar.co/?id=1f398f40cbd840398a356c65d2ac6033

It looks like the majority of the tick utilization is in "Minecraft::survive - Sync Chunk Load (SELF)". Oddly, no players were in the 'survive' world at the time, so I'm not sure what it was doing. `deadchest.log` doesn't contain any lines for the time period.

[config.yml.txt](https://github.com/apavarino/Deadchest/files/7835402/config.yml.txt)
[chestData.yml.txt](https://github.com/apavarino/Deadchest/files/7835404/chestData.yml.txt)

**Comment by assada** [comment]
same issue https://timings.aikar.co/?id=5553b0035980478fa4ab8a49c3042f15

**Comment by apavarino** [comment]
Fixed on 4.8.2 !

You can download it on discord or wait for bukkit validation staff

**Comment by assada** [comment]
https://timings.aikar.co/?id=080a92765c284022bbc8a57b0026a34b#timings

nothing changed

**Comment by apavarino** [comment]
On _Deadchest.log_ have you expired time spam message every sec ?

**Comment by assada** [comment]
No. Deadchest.log looks ok without any spam
