### ISSUE TITLE
Log Contents on Expiration

### ISSUE THREAD

**Issue by thekdub** [apavarino/Deadchest#44]
**Is your feature request related to a problem? Please describe.**
Currently, when a deadchest expires, there is no record left of what was in it. This can be problematic as there are at times circumstances which might require the return of items from a deadchest which has expired.

**Describe the solution you'd like**
I'd like to see inclusion of the contents of each deadchest logged when it expires; incluidng any and all necessary information to recreate the item(s). (type, amount, durability, enchantment(s), lore, custom name, or any other custom metadata as applicable)

**Describe alternatives you've considered**
An alternative to this would be the inclusion of a deadchest expiration event which includes reference to the ChestData for the deadchest which is expiring, that way other developers may easily build this functionality themselves.

**Additional context**

**Comment by apavarino** [comment]
Very nice idea, I put it in the roadmap !

**Comment by apavarino** [comment]
@thekdub your feature is now available on version 4.13.0 available soon on Bukkit !
