### ISSUE TITLE
Equipment with a binding curse will also be saved in Deadchest

### ISSUE THREAD

**Issue by MeowShe** [apavarino/Deadchest#51]
**Context**
- Deadchest
- Latest
- 1.19.3
- Paper

**Describe the bug**
Player's equipment with a binding curse will also be saved in DeadChest

**To Reproduce**
It's easy to reproduce.

**Expected behavior**
Equipment with a binding curse attached should always be in its original equipment slot.

**Comment by apavarino** [comment]
Thanks for the feedback !

**Comment by apavarino** [comment]
Plugins now filter this enchantement to not store stuff with it
