### ISSUE TITLE
Player experience re-claim

### ISSUE THREAD

**Issue by MartinFerenec** [apavarino/Deadchest#55]
I noticed that upon death player experience goes to 0, even when loot is re-claimed.

I suggest a feature that would allow players to re-claim the experience lost (plugin would save experience amount before death and would add it to player when re-claims the chest). 

In `config.yml` I would add these two options:

-  `save-player-experience` - true/false; allows configuring if experience is saved or not

-  `save-player-experience-penalty-percentage` - a number between 0 and 100; allows to configure how much percent of experience is deducted from player after death
Equation for `save-player-experience-penalty-percentage`: reclaimedExperience = experienceBeforeDeath * (save-player-experience-penalty-percentage/100)

**Comment by apavarino** [comment]
Hello, XP storing in now on the last version ! Percentage will come later. Thanks for the suggestion
