### ISSUE TITLE
StoreXP does store highest level a player achived not current experience

### ISSUE THREAD

**Issue by dn1s** [apavarino/Deadchest#57]
* DeadChest
* latest
* 1.20.1
* bukkit

Players end up with more experience than they had while dying.

1. /expericence set D_N1S 50 levels
2. get additional exp by killing a mob
3. remove levels by enchanting
4. die and pick up chest

**Expected behavior**
A player regains the experience he lost when dying, not highest experience he has achived.

**Screenshots**
Dying with level 47:
![2023-06-19_14 34 56](https://github.com/apavarino/Deadchest/assets/17563534/42d6d01f-fb90-47ec-a89f-5c1af30c2f82)

Got chest and ended up being level 98:
![2023-06-19_14 37 12](https://github.com/apavarino/Deadchest/assets/17563534/8d139270-85ec-4ff4-a301-f0ffb0227794)

**Comment by dn1s** [comment]
I checked the spigotmc javadocs https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.html#getTotalExperience()
It's a bit confusing

This is correct:
`This refers to the total amount of experience the player has collected over time and is not currently displayed to the client.`

This is wrong in the docs:
`Returns:
Current total experience points`

I think to fix this issue method `computeXpToStore()` has to be changed to calculate current level from `player.getLevel() + player.getExp()`

**Comment by apavarino** [comment]
Thanks for the good report ! I will look at that

**Comment by apavarino** [comment]
Fixed on 1.16.1
