### ISSUE TITLE
Add permission to picking Deadchest

### ISSUE THREAD

**Issue by apavarino** [apavarino/Deadchest#6]
Some users want to have a permission node to manage Deadchest picking

Add permission node checking if the user has the correct permission to get it. Otherwise send a message to the player to tell him that he has no right

**Comment by LaurenceBarnes** [comment]
One comment: Default should be `true` (player has the permission to break their dead chests) and it must be negated for the affected permission group (`false`)

**Comment by apavarino** [comment]
Added in 4.6.0
