### ISSUE TITLE
deadchest.log is beeing spammed with "Deadchest of [player] has expired in world" every second

### ISSUE THREAD

**Issue by ShiruHD** [apavarino/Deadchest#61]
**Context**
- DeadChest
- latest
- 1.20.1
- bukkit

**Description**
When a player's deadchest is spawned, but the player disconnects, the log file is beeing overflown with the same massage "Deadchest of [player] has expired in world", until the player reconnects to the server.

**To Reproduce**
1. Die on Server with something in your inventory.
2. Disconnect from Server.
3. Wait for the duration wich is set for the expiration-time in the config. (Default: 5 mins)
4. Look at the deadchest.log-file in the plugin folder. There you can see the spamming. (The file gets too big after some time!)
5. After logging in the Server, the log file is no longer being written to about the expiration.

**Expected behavior**
It should only be written once to the console that the deadchest is expired, regardless of the player being on the server or not.

**Screenshots**
![image](https://github.com/apavarino/Deadchest/assets/100857349/428d384d-4686-4353-b432-9d1526ec8e2a)
The first yellow TimeStamp is when the player is still on the server the entire time, the second one is when the timer is expired when the player is offline.

**Comment by apavarino** [comment]
Thanks for the report !

**Comment by apavarino** [comment]
@ShiruHD I cannot reproduce. Did someone else is online on the server when you are offline ?

**Comment by ShiruHD** [comment]
Yes, it has to be someone else online during that time so the timer gets to
0. I didn’t think about that when writing the report.

Arthur Pavarino ***@***.***> schrieb am So. 23. Juli 2023 um
18:33:

**Comment by apavarino** [comment]
Alright thanks ! I already release the version 1.16.1 but I will work on that for the next one. Thanks again !
