### ISSUE TITLE
Dead chest doesn’t spawn when player dies in void

### ISSUE THREAD

**Issue by NBS-Paste** [apavarino/Deadchest#63]
**Context**
- Plugin name
Dead chest 
- Plugin version
4.16.1
- Minecraft version
1.20.1
- Server type (Bukkit/Spigot/Paper...)
Paper 

**Describe the bug**
When certain player dies in void his dead chest doesn’t spawn.

**To Reproduce**
Player dies in void.

**Expected behavior**
Dead chest is created.

**Screenshots**
Sorry don’t have any.

Only happens to one player for some reason and can’t reproduce with any other players.

**Comment by apavarino** [comment]
Sorry i'm not able to reproduce that
