### ISSUE TITLE
Deadchest randomly doesnt spawn when deadchest type is player head

### ISSUE THREAD

**Issue by Pokerfaceuhd** [apavarino/Deadchest#67]
**Context**
- Deadchest
- 4.16.1 and 4.17.0
- 1.20.1
- Paper

**Describe the bug**
Sometimes when a player dies and the deachest type is player head it doesn't generate a deadchest due to an error 

**To Reproduce**
 1. set deadchest type to player head
 2. wait until it happens randomly

**Expected behavior**
a deadchest should generate at the players death location

**Error Log**
[loggedErrorDeadchest.txt](https://github.com/apavarino/Deadchest/files/13260784/loggedErrorDeadchest.txt)

**Comment by apavarino** [comment]
Thanks for the report but i'm not able to reproduce that ! Maybe there is an issue with some special skull player ?
