### ISSUE TITLE
Items with NBT tags don't store in the chest

### ISSUE THREAD

**Issue by Kelvium** [apavarino/Deadchest#7]
**Context**
- DeadChest 
- 4.5.0
- 1.16.5
- Tuinity

**Describe the bug**
If I have a MineTinker or SlimeFun item, it won't be stored in the dead chest

**To Reproduce**
1. Have an item with NBT tags
2. Kill yourself

**Expected behavior**
These items should be stored in the chest

**Screenshots**
maybe later

**Comment by apavarino** [comment]
Fixed in 4.70
