### ISSUE TITLE
dead chest does not appear when killed on a rail

### ISSUE THREAD

**Issue by litezin** [apavarino/Deadchest#79]
**Context**
- DeadChest
- dead-chest-4.20.0.jar
- 1.20.4
- Server type (Purpur)

**If you die on a rail the deadchest will not appear**

**To Reproduce**
1. dying on a rail

**Expected behavior**
the deadchest spawn on top of the rail without dropping items

**Screenshots**
![image](https://github.com/apavarino/Deadchest/assets/87833026/38a929af-11ac-4eaa-92e6-6a054e1d0b33)

**Comment by apavarino** [comment]
Hello, thanks for the report. Do you have **GenerateOnRails** set to **true** ?

**Comment by litezin** [comment]
Yes, the bug happens even when disabled

**Comment by apavarino** [comment]
Alright. I will look at it on next patch, thanks for the report

**Comment by apavarino** [comment]
Fixed on last version
