### ISSUE TITLE
Issue using colons in locale.yml strings

### ISSUE THREAD

**Issue by Bumber64** [apavarino/Deadchest#9]
DeadChest v4.5.1
Minecraft Java Edition 1.16.2
Spigot

Using a colon ( : ) in locale.yml causes the plugin to fail to load with an error message relating to classes or something. (Can't restart the server right now to check specifics.)

Hopefully there's a way to have colons in the string handled safely without being treated as code.

**Comment by apavarino** [comment]
@Bumber64 If you put your translation between quote, that should resolve your issue

**Comment by Bumber64** [comment]
Thanks! Would be useful to have a note about that in the yml.
